[FEAT] 스터디방 조회 페이지 UI 구성
Programmers-3th-Team-Kim/study-room-FE pull request #11
Opened 2024-09-14 11:13 UTC by NASUNJIN

## ✅ 작업 내용
스터디방 조회 페이지 UI 구성
![스크린샷 2024-09-14 오후 8 12 37](https://github.com/user-attachments/assets/29e335ee-b7fd-4559-8934-99bed0f3ccff)

## ✅ 리뷰 요청사항
스크롤 부분이 문제가 있습니다..
![스크린샷 2024-09-14 오후 8 13 23](https://github.com/user-attachments/assets/b0fa34df-a964-4563-944d-58a8fec86b20)

## 📢 관련 이슈
#8

2024-09-15 17:57 UTC, bang-wol reviewed
수고하셨습니당 🥹
스타일은 제대로 분리 해주시고 주석은 최소화 하는 게 좋을 것 같아요!

2024-09-15 17:57 UTC, bang-wol commented on src/App.tsx
선진님 이 부분은 App 파일이 아니라 라우터 파일에 있어야 할 내용 같아요!

2024-09-15 17:57 UTC, bang-wol commented on src/components/button/SCreateButton.tsx
> +import { ButtonSize } from "../../styles/theme";
```suggestion
import { ButtonSize } from "@/styles/theme";
```
절대 경로 적용해주시면 좋을 것 같습니당

2024-09-15 17:57 UTC, bang-wol commented on src/pages/SearchStudyRoom.tsx
여기두..

2024-09-15 17:57 UTC, bang-wol commented on src/components/studyroom/item/StudyGrid.tsx
여기 스타일들 StudyGrid.style.ts 파일로 따로 빼주는 게 저희가 정했던 구조인 것 같습니당!

2024-09-15 17:57 UTC, bang-wol commented on src/components/studyroom/item/StudyItem.tsx
여기도 StudyItem.style.ts..

2024-09-15 17:57 UTC, bang-wol commented on src/components/button/SCreateButton.tsx
> +      <div className="icon">{Icon && <Icon size={iconSize} />}</div>
```suggestion
{Icon && (
    <div className="icon">
      <Icon size={iconSize} />
    </div>
  )}
```
  
아이콘 없을 때 div 자체를 렌더링 안 하는게 좋을 것 같아요!

2024-09-15 17:57 UTC, bang-wol commented on src/components/button/SCreateButton.tsx
> +function SCreateButton({ label, size = "small", Icon, borderRadius, fontSize, iconSize = 16, ...props}: ButtonProps) {
fontSize도 그냥 기본 값으로 주면 어떨까요...?

2024-09-15 17:57 UTC, bang-wol commented on src/components/studyroom/button/CreateButton.tsx
> +// import { useState } from "react";
사용하지 않는 코드는 주석 처리하는 것 보단 그냥 지우는 게 나을 것 같습니다! 나중에 추가해야 할 일이라면 그냥 `// @TODO 모달 컴포넌트 추가` 정도만 남겨주시면 좋을 것 같아요!

2024-09-15 17:57 UTC, bang-wol commented on src/components/studyroom/button/CreateButton.tsx
> +      {/* 모달 컴포넌트 추가 */}
CreateButton이랑 SCreateButton이 있는데 뭔가 두 개 역할이랑 이름이 명확하지가 않은 것 같아요..?! 

CreateButtonStyle은 그냥 버튼을 감싸주기만 하는 것 같은데 CreateButton, SCreateButton은 그냥 하나만 있어도 되지 않을까요? 

모달 때문에 두 개를 따로 만드신 것 같아 보여요! 근데 버튼은 모달을 열기 위한 트리거 역할만 하는데, 버튼 컴포넌트 안에 모달 컴포넌트 상태 관리가 있는 건 뭔가 컴포넌트 분리가 제대로 안 되는 것 같아요. 

버튼 말고 상위 컴포넌트에서 모달 컴포넌트를 제어하는 게 맞다는 생각이 듭니당...!

2024-09-16 09:18 UTC, NASUNJIN commented on src/App.tsx
엇 그렇네요 라우터로 바꿔놓겠습니다

2024-09-16 09:26 UTC, NASUNJIN commented on src/components/studyroom/button/CreateButton.tsx
> +      {/* 모달 컴포넌트 추가 */}
SCreateButton은 온라인 스터디 내에서 작동하는 button 때문에 만들어놓은거고 (원래는 Button이었는데 수빈님이 Button으로 이미 만들어놔서 에러날까봐 이름을 바꿨습니다) createButton은 스터디방 개설 버튼으로 만들었습니다.

나중엔 온라인스터디 방안에 들어간느 추가하기, 시작, 나가기 버튼도 StartButton 이런식으로 만드려고 하는데 따로 컴포넌트를 안만드는게 좋을까요?

2024-09-16 09:34 UTC, NASUNJIN commented on src/components/button/SCreateButton.tsx
> +function SCreateButton({ label, size = "small", Icon, borderRadius, fontSize, iconSize = 16, ...props}: ButtonProps) {
혹시 기본 값 사이즈가 크기가 어느정도일까요??
저도 처음에 사이즈 안받아도 크기 마음대로 설정할 수 있게 하고싶었는데 안되더라구요ㅜㅜ

2024-09-16 13:03 UTC, bang-wol commented on src/components/studyroom/button/CreateButton.tsx
> +      {/* 모달 컴포넌트 추가 */}
버튼 컴포넌트 하나를 재사용 가능하게 만들어서 사용하는 건 어떨까요? 
사용되는 크기만 지정해놓으면 그렇게 만들 수 있지 않을까요?! 들어가는 아이콘 정도만 추가해주면요..!
개인적으로 create, start, exit 버튼이 다 따로 있는 것보다 좀 더 효율적일 것 같단 생각이 듭니다!

2024-09-16 17:47 UTC, JSLEE753 commented
제 뷰포트는 1920*953인데 사진처럼 하단에 여백이 출력됩니다..!

![1](https://github.com/user-attachments/assets/d416e369-9804-47b2-8a56-2d986cd8199f)

2024-09-16 18:08 UTC, JSLEE753 requested changes

2024-09-16 18:08 UTC, JSLEE753 commented on src/components/button/SCreateButton.style.ts
> +export const SCreateButtonStyle = styled.button<{ size: ButtonSize; borderRadius?: string; fontSize?: string; }>`
이 부분에 shouldForwardProp 적용시켜줘야 할 것 같아요!
브라우저 콘솔에서 경고가 나타나네용
![2](https://github.com/user-attachments/assets/7393c0f3-8f7f-4b06-aa61-c95e20338974)


```ts
export const SCreateButtonStyle = styled.button.withConfig({
  shouldForwardProp: (prop) => !['borderRadius'].includes(prop),
})<{
  size: ButtonSize;
  borderRadius?: string;
  fontSize?: string;
}>`
```

2024-09-16 18:08 UTC, JSLEE753 commented on src/components/studyroom/item/StudyItem.style.ts
> +export const ItemContainer = styled.div<{ imageUrl?: string }>`
이 부분도 마찬가지로 shouldForwardProp 적용시켜줘야 할 것 같아요!

2024-09-17 02:04 UTC, chchaeun approved these changes

2024-09-17 02:04 UTC, chchaeun commented on src/components/studyroom/filter/CheckBox.style.ts
> +	.checkbox-wrap {
styled component와 css를 같이 이용하는 게 어색해보여요. 컴포넌트 스타일링 시 전부 styled component를 이용해서 하는 게 깔끔하다고 생각합니다!

2024-09-17 02:04 UTC, chchaeun commented on src/components/studyroom/item/StudyGrid.tsx
> +const dummyData = [
dummyData 대신 msw와 같은 api 모킹 툴을 써보는 건 어떨까요? 나중에 api가 다 개발되고 연동하려면 그것도 시간이 오래 걸리기 때문에 모킹 서버를 만들어두고 연동 코드를 미리 작성해두는 게 좋을 것 같아요. msw도 러닝커브가 높은 편은 아니지만 조금 더 쉬운 json-server도 괜찮습니다!

2024-09-18 10:33 UTC, NASUNJIN commented on src/components/studyroom/item/StudyGrid.tsx
> +const dummyData = [
곧 api가 만들어질것 같아서 일단 이렇게 하겠습니다!

2024-09-18 11:07 UTC, JSLEE753 approved these changes

2024-09-18 11:09 UTC, merged